load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "hook",
    srcs = ["hook.go"],
    importpath = "github.com/m-nny/universe/ent/hook",
    visibility = ["//visibility:public"],
    deps = ["//ent"],
)
