load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "jsoncache",
    srcs = ["jsoncache.go"],
    data = ["//data:json_cache"],
    importpath = "github.com/m-nny/universe/lib/jsoncache",
    visibility = ["//visibility:public"],
)
