load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "runtime",
    srcs = ["runtime.go"],
    importpath = "github.com/m-nny/universe/ent/runtime",
    visibility = ["//visibility:public"],
)
