// Code generated by ent, DO NOT EDIT.

package track

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/m-nny/universe/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Track {
	return predicate.Track(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Track {
	return predicate.Track(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Track {
	return predicate.Track(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Track {
	return predicate.Track(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Track {
	return predicate.Track(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Track {
	return predicate.Track(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Track {
	return predicate.Track(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldName, v))
}

// TrackNumber applies equality check predicate on the "trackNumber" field. It's identical to TrackNumberEQ.
func TrackNumber(v int) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldTrackNumber, v))
}

// SimplifiedName applies equality check predicate on the "simplifiedName" field. It's identical to SimplifiedNameEQ.
func SimplifiedName(v string) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldSimplifiedName, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Track {
	return predicate.Track(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Track {
	return predicate.Track(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Track {
	return predicate.Track(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Track {
	return predicate.Track(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Track {
	return predicate.Track(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Track {
	return predicate.Track(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Track {
	return predicate.Track(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Track {
	return predicate.Track(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Track {
	return predicate.Track(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Track {
	return predicate.Track(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Track {
	return predicate.Track(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Track {
	return predicate.Track(sql.FieldContainsFold(FieldName, v))
}

// TrackNumberEQ applies the EQ predicate on the "trackNumber" field.
func TrackNumberEQ(v int) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldTrackNumber, v))
}

// TrackNumberNEQ applies the NEQ predicate on the "trackNumber" field.
func TrackNumberNEQ(v int) predicate.Track {
	return predicate.Track(sql.FieldNEQ(FieldTrackNumber, v))
}

// TrackNumberIn applies the In predicate on the "trackNumber" field.
func TrackNumberIn(vs ...int) predicate.Track {
	return predicate.Track(sql.FieldIn(FieldTrackNumber, vs...))
}

// TrackNumberNotIn applies the NotIn predicate on the "trackNumber" field.
func TrackNumberNotIn(vs ...int) predicate.Track {
	return predicate.Track(sql.FieldNotIn(FieldTrackNumber, vs...))
}

// TrackNumberGT applies the GT predicate on the "trackNumber" field.
func TrackNumberGT(v int) predicate.Track {
	return predicate.Track(sql.FieldGT(FieldTrackNumber, v))
}

// TrackNumberGTE applies the GTE predicate on the "trackNumber" field.
func TrackNumberGTE(v int) predicate.Track {
	return predicate.Track(sql.FieldGTE(FieldTrackNumber, v))
}

// TrackNumberLT applies the LT predicate on the "trackNumber" field.
func TrackNumberLT(v int) predicate.Track {
	return predicate.Track(sql.FieldLT(FieldTrackNumber, v))
}

// TrackNumberLTE applies the LTE predicate on the "trackNumber" field.
func TrackNumberLTE(v int) predicate.Track {
	return predicate.Track(sql.FieldLTE(FieldTrackNumber, v))
}

// SimplifiedNameEQ applies the EQ predicate on the "simplifiedName" field.
func SimplifiedNameEQ(v string) predicate.Track {
	return predicate.Track(sql.FieldEQ(FieldSimplifiedName, v))
}

// SimplifiedNameNEQ applies the NEQ predicate on the "simplifiedName" field.
func SimplifiedNameNEQ(v string) predicate.Track {
	return predicate.Track(sql.FieldNEQ(FieldSimplifiedName, v))
}

// SimplifiedNameIn applies the In predicate on the "simplifiedName" field.
func SimplifiedNameIn(vs ...string) predicate.Track {
	return predicate.Track(sql.FieldIn(FieldSimplifiedName, vs...))
}

// SimplifiedNameNotIn applies the NotIn predicate on the "simplifiedName" field.
func SimplifiedNameNotIn(vs ...string) predicate.Track {
	return predicate.Track(sql.FieldNotIn(FieldSimplifiedName, vs...))
}

// SimplifiedNameGT applies the GT predicate on the "simplifiedName" field.
func SimplifiedNameGT(v string) predicate.Track {
	return predicate.Track(sql.FieldGT(FieldSimplifiedName, v))
}

// SimplifiedNameGTE applies the GTE predicate on the "simplifiedName" field.
func SimplifiedNameGTE(v string) predicate.Track {
	return predicate.Track(sql.FieldGTE(FieldSimplifiedName, v))
}

// SimplifiedNameLT applies the LT predicate on the "simplifiedName" field.
func SimplifiedNameLT(v string) predicate.Track {
	return predicate.Track(sql.FieldLT(FieldSimplifiedName, v))
}

// SimplifiedNameLTE applies the LTE predicate on the "simplifiedName" field.
func SimplifiedNameLTE(v string) predicate.Track {
	return predicate.Track(sql.FieldLTE(FieldSimplifiedName, v))
}

// SimplifiedNameContains applies the Contains predicate on the "simplifiedName" field.
func SimplifiedNameContains(v string) predicate.Track {
	return predicate.Track(sql.FieldContains(FieldSimplifiedName, v))
}

// SimplifiedNameHasPrefix applies the HasPrefix predicate on the "simplifiedName" field.
func SimplifiedNameHasPrefix(v string) predicate.Track {
	return predicate.Track(sql.FieldHasPrefix(FieldSimplifiedName, v))
}

// SimplifiedNameHasSuffix applies the HasSuffix predicate on the "simplifiedName" field.
func SimplifiedNameHasSuffix(v string) predicate.Track {
	return predicate.Track(sql.FieldHasSuffix(FieldSimplifiedName, v))
}

// SimplifiedNameEqualFold applies the EqualFold predicate on the "simplifiedName" field.
func SimplifiedNameEqualFold(v string) predicate.Track {
	return predicate.Track(sql.FieldEqualFold(FieldSimplifiedName, v))
}

// SimplifiedNameContainsFold applies the ContainsFold predicate on the "simplifiedName" field.
func SimplifiedNameContainsFold(v string) predicate.Track {
	return predicate.Track(sql.FieldContainsFold(FieldSimplifiedName, v))
}

// HasSavedBy applies the HasEdge predicate on the "savedBy" edge.
func HasSavedBy() predicate.Track {
	return predicate.Track(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, SavedByTable, SavedByPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSavedByWith applies the HasEdge predicate on the "savedBy" edge with a given conditions (other predicates).
func HasSavedByWith(preds ...predicate.User) predicate.Track {
	return predicate.Track(func(s *sql.Selector) {
		step := newSavedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAlbum applies the HasEdge predicate on the "album" edge.
func HasAlbum() predicate.Track {
	return predicate.Track(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AlbumTable, AlbumColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAlbumWith applies the HasEdge predicate on the "album" edge with a given conditions (other predicates).
func HasAlbumWith(preds ...predicate.Album) predicate.Track {
	return predicate.Track(func(s *sql.Selector) {
		step := newAlbumStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasArtists applies the HasEdge predicate on the "artists" edge.
func HasArtists() predicate.Track {
	return predicate.Track(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ArtistsTable, ArtistsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArtistsWith applies the HasEdge predicate on the "artists" edge with a given conditions (other predicates).
func HasArtistsWith(preds ...predicate.Artist) predicate.Track {
	return predicate.Track(func(s *sql.Selector) {
		step := newArtistsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Track) predicate.Track {
	return predicate.Track(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Track) predicate.Track {
	return predicate.Track(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Track) predicate.Track {
	return predicate.Track(sql.NotPredicates(p))
}
