load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "hitcounter",
    srcs = ["hitcounter.go"],
    importpath = "github.com/m-nny/universe/lib/utils/hitcounter",
    visibility = ["//visibility:public"],
)
