load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "maputils",
    srcs = ["maputils.go"],
    importpath = "github.com/m-nny/universe/lib/utils/maputils",
    visibility = ["//visibility:public"],
)
