// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PlaylistsColumns holds the columns for the "playlists" table.
	PlaylistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "snaphot_id", Type: field.TypeString},
		{Name: "user_playlists", Type: field.TypeString, Nullable: true},
	}
	// PlaylistsTable holds the schema information for the "playlists" table.
	PlaylistsTable = &schema.Table{
		Name:       "playlists",
		Columns:    PlaylistsColumns,
		PrimaryKey: []*schema.Column{PlaylistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playlists_users_playlists",
				Columns:    []*schema.Column{PlaylistsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TracksColumns holds the columns for the "tracks" table.
	TracksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "artist_names", Type: field.TypeJSON},
		{Name: "artist_ids", Type: field.TypeJSON},
	}
	// TracksTable holds the schema information for the "tracks" table.
	TracksTable = &schema.Table{
		Name:       "tracks",
		Columns:    TracksColumns,
		PrimaryKey: []*schema.Column{TracksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "spotify_token", Type: field.TypeJSON},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserSavedTracksColumns holds the columns for the "user_savedTracks" table.
	UserSavedTracksColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString},
		{Name: "track_id", Type: field.TypeString},
	}
	// UserSavedTracksTable holds the schema information for the "user_savedTracks" table.
	UserSavedTracksTable = &schema.Table{
		Name:       "user_savedTracks",
		Columns:    UserSavedTracksColumns,
		PrimaryKey: []*schema.Column{UserSavedTracksColumns[0], UserSavedTracksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_savedTracks_user_id",
				Columns:    []*schema.Column{UserSavedTracksColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_savedTracks_track_id",
				Columns:    []*schema.Column{UserSavedTracksColumns[1]},
				RefColumns: []*schema.Column{TracksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PlaylistsTable,
		TracksTable,
		UsersTable,
		UserSavedTracksTable,
	}
)

func init() {
	PlaylistsTable.ForeignKeys[0].RefTable = UsersTable
	UserSavedTracksTable.ForeignKeys[0].RefTable = UsersTable
	UserSavedTracksTable.ForeignKeys[1].RefTable = TracksTable
}
