// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/m-nny/universe/ent/album"
	"github.com/m-nny/universe/ent/track"
)

// Track is the model entity for the Track schema.
type Track struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SpotifyIds holds the value of the "spotifyIds" field.
	SpotifyIds []string `json:"spotifyIds,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TrackNumber holds the value of the "trackNumber" field.
	TrackNumber int `json:"trackNumber,omitempty"`
	// SimplifiedName holds the value of the "simplifiedName" field.
	SimplifiedName string `json:"simplifiedName,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TrackQuery when eager-loading is set.
	Edges        TrackEdges `json:"edges"`
	album_tracks *int
	selectValues sql.SelectValues
}

// TrackEdges holds the relations/edges for other nodes in the graph.
type TrackEdges struct {
	// SavedBy holds the value of the savedBy edge.
	SavedBy []*User `json:"savedBy,omitempty"`
	// Album holds the value of the album edge.
	Album *Album `json:"album,omitempty"`
	// Artists holds the value of the artists edge.
	Artists []*Artist `json:"artists,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SavedByOrErr returns the SavedBy value or an error if the edge
// was not loaded in eager-loading.
func (e TrackEdges) SavedByOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.SavedBy, nil
	}
	return nil, &NotLoadedError{edge: "savedBy"}
}

// AlbumOrErr returns the Album value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TrackEdges) AlbumOrErr() (*Album, error) {
	if e.loadedTypes[1] {
		if e.Album == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: album.Label}
		}
		return e.Album, nil
	}
	return nil, &NotLoadedError{edge: "album"}
}

// ArtistsOrErr returns the Artists value or an error if the edge
// was not loaded in eager-loading.
func (e TrackEdges) ArtistsOrErr() ([]*Artist, error) {
	if e.loadedTypes[2] {
		return e.Artists, nil
	}
	return nil, &NotLoadedError{edge: "artists"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Track) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case track.FieldSpotifyIds:
			values[i] = new([]byte)
		case track.FieldID, track.FieldTrackNumber:
			values[i] = new(sql.NullInt64)
		case track.FieldName, track.FieldSimplifiedName:
			values[i] = new(sql.NullString)
		case track.ForeignKeys[0]: // album_tracks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Track fields.
func (t *Track) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case track.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case track.FieldSpotifyIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field spotifyIds", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &t.SpotifyIds); err != nil {
					return fmt.Errorf("unmarshal field spotifyIds: %w", err)
				}
			}
		case track.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				t.Name = value.String
			}
		case track.FieldTrackNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trackNumber", values[i])
			} else if value.Valid {
				t.TrackNumber = int(value.Int64)
			}
		case track.FieldSimplifiedName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field simplifiedName", values[i])
			} else if value.Valid {
				t.SimplifiedName = value.String
			}
		case track.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field album_tracks", value)
			} else if value.Valid {
				t.album_tracks = new(int)
				*t.album_tracks = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Track.
// This includes values selected through modifiers, order, etc.
func (t *Track) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QuerySavedBy queries the "savedBy" edge of the Track entity.
func (t *Track) QuerySavedBy() *UserQuery {
	return NewTrackClient(t.config).QuerySavedBy(t)
}

// QueryAlbum queries the "album" edge of the Track entity.
func (t *Track) QueryAlbum() *AlbumQuery {
	return NewTrackClient(t.config).QueryAlbum(t)
}

// QueryArtists queries the "artists" edge of the Track entity.
func (t *Track) QueryArtists() *ArtistQuery {
	return NewTrackClient(t.config).QueryArtists(t)
}

// Update returns a builder for updating this Track.
// Note that you need to call Track.Unwrap() before calling this method if this Track
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Track) Update() *TrackUpdateOne {
	return NewTrackClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Track entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Track) Unwrap() *Track {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Track is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Track) String() string {
	var builder strings.Builder
	builder.WriteString("Track(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("spotifyIds=")
	builder.WriteString(fmt.Sprintf("%v", t.SpotifyIds))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(t.Name)
	builder.WriteString(", ")
	builder.WriteString("trackNumber=")
	builder.WriteString(fmt.Sprintf("%v", t.TrackNumber))
	builder.WriteString(", ")
	builder.WriteString("simplifiedName=")
	builder.WriteString(t.SimplifiedName)
	builder.WriteByte(')')
	return builder.String()
}

// Tracks is a parsable slice of Track.
type Tracks []*Track
