load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = [
        "fp.go",
        "map.go",
    ],
    importpath = "github.com/m-nny/universe/lib/utils",
    visibility = ["//visibility:public"],
)
