load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "slices",
    srcs = ["slices.go"],
    importpath = "github.com/m-nny/universe/lib/utils/slices",
    visibility = ["//visibility:public"],
)
