filegroup(
    name = "ent_db",
    data = ["ent.db"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gorm_db",
    data = ["gorm.db"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "json_cache",
    data = ["cache"],  ## intentionally passing whole folder
    visibility = ["//visibility:public"],
)
