filegroup(
    name = "ent_db",
    srcs = ["ent.db"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "json_cache",
    srcs = glob([
        "cache/*.json",
    ]),
    visibility = ["//visibility:public"],
)