load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sliceutils",
    srcs = ["sliceutils.go"],
    importpath = "github.com/m-nny/universe/lib/utils/sliceutils",
    visibility = ["//visibility:public"],
)
