// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Playlist is the predicate function for playlist builders.
type Playlist func(*sql.Selector)

// Track is the predicate function for track builders.
type Track func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
